# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - build-essential
    - make
    - pkg-config
    - cmake
    - ninja-build
  jobs:
    pre_install:
      - git clone --depth 1 --branch release-3.2.16 https://github.com/libsdl-org/SDL.git sdl_repo
      - cmake -S sdl_repo -B sdl_build -D CMAKE_INSTALL_PREFIX=~/.local
      - cmake --build sdl_build --config Debug
      - cmake --install sdl_build

submodules:
  include: all

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats: all

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
